version: 0.0
os: windows
files:
  - source: \SendUDP\bin\Debug\
    destination: C:\Users\Administrator\Desktop\RabbitMQ
hooks:
  BeforeInstall:
     - location:
       runas: Administrator
       timeout: 900
 
