version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Desktop\RabbitMQ
hooks:
  BeforeInstall:
     - location: build.bat
       runas: Administrator
       timeout: 900
     - location: build.bat
       runas: Administrator
       timeout: 900
  
   

