version: 0.0
os: windows
files:
  - source: \Desktop
    destination: C:\Users\Administrator\Desktop
hooks:
  BeforeInstall:
     - location: build.bat
       runas: Administrator
       timeout: 900
